import { LayoutGridIcon as LayoutGrid, MenuIcon as Menu } from "@animateicons/react/lucide";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { useSidebar } from "@/hooks/use-sidebar";
import { HeaderActions } from "./HeaderActions";
import { HeaderSearch } from "./HeaderSearch";
import { AppSidebar } from "./AppSidebar";
import { cn } from "@/lib/utils";
import { useAnimatedIcon } from "@/hooks/use-animated-icon";

export function AppHeader() { const { state, isMobile, openMobile, setOpenMobile, toggleSidebar } = useSidebar(); const menuIcon = useAnimatedIcon(); const gridIcon = useAnimatedIcon(); return <header className={cn("fixed left-0 right-0 top-0 z-20 flex h-[var(--header-height)] items-center justify-between border-b border-[var(--border-soft)] bg-white px-5 shadow-[0_2px_6px_rgba(30,40,55,0.045)] transition-[left] duration-150 ease-out md:left-[var(--sidebar-collapsed-width)] md:px-8", state === "expanded" && "xl:left-[var(--sidebar-width)]")}><div className="flex min-w-0 items-center gap-3 sm:gap-6">{isMobile ? <Sheet open={openMobile} onOpenChange={setOpenMobile}><SheetTrigger asChild><Button variant="ghost" size="icon" aria-label="Open navigation" onMouseEnter={menuIcon.onMouseEnter} onMouseLeave={menuIcon.onMouseLeave} className="size-10 rounded-full bg-[var(--brand-soft)] text-[var(--brand)] transition-transform duration-150 active:scale-95"><Menu ref={menuIcon.ref} size={20} duration={0.7} /></Button></SheetTrigger><SheetContent className="w-[288px] p-0" side="left"><AppSidebar mobile /></SheetContent></Sheet> : <Button variant="ghost" size="icon" aria-label="Toggle sidebar" onClick={toggleSidebar} onMouseEnter={gridIcon.onMouseEnter} onMouseLeave={gridIcon.onMouseLeave} className="group/grid size-[42px] rounded-full bg-[var(--brand-soft)] text-[var(--brand)] shadow-[inset_0_0_0_1px_rgba(17,107,111,0.025)] transition-[background-color,transform,box-shadow] duration-150 ease-out hover:-translate-y-px hover:bg-[#d6ebec] hover:shadow-[0_3px_7px_rgba(17,107,111,.12)] active:translate-y-0 active:scale-[.94] active:shadow-inner"><LayoutGrid ref={gridIcon.ref} size={20} duration={0.7} /></Button>}<HeaderSearch /></div><HeaderActions /></header>; }
