import { useRef } from "react";
import { ChevronDownIcon as ChevronDown, ChevronRightIcon as ChevronRight } from "@animateicons/react/lucide";
import { Link, useLocation } from "react-router-dom";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { SidebarMenuButton, SidebarMenuItem as MenuItem, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem } from "@/components/ui/sidebar";
import { Badge } from "@/components/ui/badge";
import type { AnimatedIconHandle, NavigationItem } from "@/config/navigation";
import { useSidebar } from "@/hooks/use-sidebar";
import { cn } from "@/lib/utils";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

function isItemActive(item: NavigationItem, pathname: string) { return Boolean((item.url && (item.url === pathname || pathname.startsWith(`${item.url}/`))) || item.children?.some((child) => child.url === pathname)); }
export function SidebarMenuItem({ item }: { item: NavigationItem }) { const { state, isMobile, setOpenMobile } = useSidebar(); const location = useLocation(); const active = isItemActive(item, location.pathname); const hasChildren = Boolean(item.children?.length); const iconRef = useRef<AnimatedIconHandle>(null); const animateIcon = () => iconRef.current?.startAnimation(); const resetIcon = () => iconRef.current?.stopAnimation(); const handleNavigation = () => { if (isMobile) setOpenMobile(false); }; const content = <><span className={cn("flex min-w-0 flex-1 items-center gap-2.5", state === "collapsed" && "flex-none justify-center")}><item.icon ref={iconRef} className="size-5 shrink-0" size={20} duration={0.7} /><span className={cn("min-w-0 flex-1 truncate leading-5", state === "collapsed" && "hidden")}>{item.title}</span></span>{state !== "collapsed" && <span className="ml-auto flex shrink-0 items-center gap-1.5">{item.badge && <Badge className={cn("h-[21px] min-w-[21px] justify-center px-1.5 text-[11px] leading-none", item.badge.variant === "danger" && "bg-[var(--danger)] text-white shadow-[0_2px_4px_rgba(236,82,97,.22)]", item.badge.variant === "warning" && "bg-[var(--warning)] text-white", item.badge.variant === "success" && "bg-[var(--success)] text-white")}>{item.badge.text}</Badge>}{hasChildren && (active ? <ChevronDown className="size-4" size={16} duration={0.6} /> : <ChevronRight className="size-4" size={16} duration={0.6} />)}</span>}</>;
  if (state === "collapsed") { const compactButton = <SidebarMenuButton asChild isActive={active} onMouseEnter={animateIcon} onMouseLeave={resetIcon} className="mx-auto size-11 w-11 justify-center px-0"><Link aria-current={active ? "page" : undefined} onClick={handleNavigation} to={item.url ?? item.children?.[0]?.url ?? "#"}>{content}</Link></SidebarMenuButton>; return <MenuItem><TooltipProvider delayDuration={200}><Tooltip><TooltipTrigger asChild>{compactButton}</TooltipTrigger><TooltipContent side="right">{item.title}</TooltipContent></Tooltip></TooltipProvider></MenuItem>; }
  if (!hasChildren) { const button = <SidebarMenuButton asChild isActive={active} onMouseEnter={animateIcon} onMouseLeave={resetIcon}><Link aria-current={active ? "page" : undefined} onClick={handleNavigation} to={item.url ?? "#"}>{content}</Link></SidebarMenuButton>; return <MenuItem>{button}</MenuItem>; }
  return <Collapsible defaultOpen={active} asChild><MenuItem><CollapsibleTrigger asChild><SidebarMenuButton isActive={active} onMouseEnter={animateIcon} onMouseLeave={resetIcon}>{content}</SidebarMenuButton></CollapsibleTrigger><CollapsibleContent><SidebarMenuSub>{item.children?.map((child) => <SidebarMenuSubItem key={child.title}><SidebarMenuSubButton asChild isActive={location.pathname === child.url}><Link aria-current={location.pathname === child.url ? "page" : undefined} onClick={handleNavigation} to={child.url ?? "#"}>{child.title}</Link></SidebarMenuSubButton></SidebarMenuSubItem>)}</SidebarMenuSub></CollapsibleContent></MenuItem></Collapsible>; }
