import type { LucideIcon } from "lucide-react";
import { MessageCircle, UserRound, MessagesSquare, Megaphone, Webhook } from "lucide-react";
import type { AutomationTriggerType } from "@/types/automation";

export type AutomationTriggerDefinition = { type: AutomationTriggerType; label: string; description: string; category: string; icon: LucideIcon; fields: Array<{ value: string; label: string; kind?: "text" | "number" | "select" }> };
export const automationTriggers: AutomationTriggerDefinition[] = [
  { type: "MESSAGE_RECEIVED", label: "New WhatsApp message received", description: "Runs whenever a customer sends your WhatsApp number a message.", category: "WhatsApp", icon: MessageCircle, fields: [{ value: "message.text", label: "Message Text", kind: "text" }, { value: "message.type", label: "Message Type", kind: "select" }, { value: "contact.phone", label: "Phone Number", kind: "text" }, { value: "contact.name", label: "Contact Name", kind: "text" }, { value: "contact.tags", label: "Contact Tag", kind: "text" }, { value: "contact.custom", label: "Contact Custom Field", kind: "text" }, { value: "conversation.status", label: "Conversation Status", kind: "select" }, { value: "conversation.assignedAgent", label: "Assigned Agent", kind: "select" }, { value: "conversation.assignedTeam", label: "Assigned Team", kind: "select" }] },
  { type: "MESSAGE_SENT", label: "Message sent", description: "Runs when a message is sent from your WhatsApp number.", category: "WhatsApp", icon: MessageCircle, fields: [{ value: "message.text", label: "Message Text", kind: "text" }, { value: "contact.name", label: "Contact Name", kind: "text" }] },
  { type: "CUSTOMER_REPLIED", label: "Customer replied", description: "Runs when a customer replies to a conversation.", category: "WhatsApp", icon: MessageCircle, fields: [{ value: "message.text", label: "Message Text", kind: "text" }, { value: "contact.tags", label: "Contact Tag", kind: "text" }] },
  { type: "TEMPLATE_DELIVERED", label: "Template message delivered", description: "Runs when a WhatsApp template is delivered.", category: "WhatsApp", icon: MessageCircle, fields: [{ value: "message.template", label: "Template Name", kind: "text" }] },
  { type: "TEMPLATE_READ", label: "Template message read", description: "Runs when a customer reads a template message.", category: "WhatsApp", icon: MessageCircle, fields: [{ value: "message.template", label: "Template Name", kind: "text" }] },
  { type: "TEMPLATE_FAILED", label: "Template message failed", description: "Runs when a template message fails to send.", category: "WhatsApp", icon: MessageCircle, fields: [{ value: "message.template", label: "Template Name", kind: "text" }] },
  { type: "CONTACT_CREATED", label: "Contact created", description: "Runs when a new contact is added to your workspace.", category: "Contact", icon: UserRound, fields: [{ value: "contact.name", label: "Contact Name", kind: "text" }, { value: "contact.tags", label: "Contact Tag", kind: "text" }] },
  { type: "CONTACT_UPDATED", label: "Contact updated", description: "Runs when contact details change.", category: "Contact", icon: UserRound, fields: [{ value: "contact.name", label: "Contact Name", kind: "text" }, { value: "contact.custom", label: "Contact Custom Field", kind: "text" }] },
  { type: "TAG_ADDED", label: "Tag added", description: "Runs when a tag is added to a contact.", category: "Contact", icon: UserRound, fields: [{ value: "contact.tags", label: "Contact Tag", kind: "text" }] },
  { type: "TAG_REMOVED", label: "Tag removed", description: "Runs when a tag is removed from a contact.", category: "Contact", icon: UserRound, fields: [{ value: "contact.tags", label: "Contact Tag", kind: "text" }] },
  { type: "CUSTOM_FIELD_UPDATED", label: "Custom field updated", description: "Runs when a contact custom field changes.", category: "Contact", icon: UserRound, fields: [{ value: "contact.custom", label: "Contact Custom Field", kind: "text" }] },
  { type: "CONVERSATION_OPENED", label: "Conversation opened", description: "Runs when a conversation is opened.", category: "Conversation", icon: MessagesSquare, fields: [{ value: "conversation.status", label: "Conversation Status", kind: "select" }] },
  { type: "CONVERSATION_CLOSED", label: "Conversation closed", description: "Runs when a conversation is closed.", category: "Conversation", icon: MessagesSquare, fields: [{ value: "conversation.status", label: "Conversation Status", kind: "select" }] },
  { type: "CONVERSATION_ASSIGNED", label: "Conversation assigned", description: "Runs when a conversation is assigned.", category: "Conversation", icon: MessagesSquare, fields: [{ value: "conversation.assignedAgent", label: "Assigned Agent", kind: "select" }, { value: "conversation.assignedTeam", label: "Assigned Team", kind: "select" }] },
  { type: "CONVERSATION_UNASSIGNED", label: "Conversation unassigned", description: "Runs when a conversation is unassigned.", category: "Conversation", icon: MessagesSquare, fields: [{ value: "conversation.assignedAgent", label: "Assigned Agent", kind: "select" }] },
  { type: "CAMPAIGN_MESSAGE_SENT", label: "Campaign message sent", description: "Runs when a campaign message is sent.", category: "Campaign", icon: Megaphone, fields: [{ value: "campaign.name", label: "Campaign Name", kind: "text" }] },
  { type: "CAMPAIGN_REPLIED", label: "Customer replied to campaign", description: "Runs when a customer replies to a campaign.", category: "Campaign", icon: Megaphone, fields: [{ value: "campaign.name", label: "Campaign Name", kind: "text" }] },
  { type: "CAMPAIGN_CTA_CLICKED", label: "Customer clicked CTA", description: "Runs when a customer clicks a campaign call to action.", category: "Campaign", icon: Megaphone, fields: [{ value: "campaign.name", label: "Campaign Name", kind: "text" }] },
  { type: "WEBHOOK_RECEIVED", label: "Webhook received", description: "Runs when an external webhook is received.", category: "External / API", icon: Webhook, fields: [{ value: "webhook.event", label: "Event Name", kind: "text" }] },
  { type: "CUSTOM_EVENT_RECEIVED", label: "Custom event received", description: "Runs when your integration emits a custom event.", category: "External / API", icon: Webhook, fields: [{ value: "event.name", label: "Event Name", kind: "text" }] },
];
export function getTriggerDefinition(type: AutomationTriggerType | undefined) { return automationTriggers.find((trigger) => trigger.type === type); }
