import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cn } from "@/lib/utils";
import { SidebarProvider as SidebarStateProvider, useSidebar } from "@/hooks/use-sidebar";

const SidebarProvider = SidebarStateProvider;
function Sidebar({ children, className, ...props }: React.HTMLAttributes<HTMLElement>) {
  const { state } = useSidebar();
  return <aside data-state={state} className={cn("fixed inset-y-0 left-0 z-30 hidden w-[var(--sidebar-width)] flex-col border-r border-white/10 bg-[linear-gradient(180deg,#064e3b_0%,#043f32_50%,#052e27_100%)] shadow-[2px_0_8px_rgba(5,46,39,0.10)] transition-[width] duration-150 ease-out md:flex", state === "collapsed" && "w-[var(--sidebar-collapsed-width)]", className)} {...props}>{children}</aside>;
}
function SidebarHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("shrink-0", className)} {...props} />; }
function SidebarContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("scrollbar-subtle min-h-0 flex-1 overflow-y-auto", className)} {...props} />; }
function SidebarFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("shrink-0", className)} {...props} />; }
function SidebarGroup({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("relative w-full min-w-0 px-3", className)} {...props} />; }
function SidebarGroupLabel({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { const { state } = useSidebar(); return <div className={cn("mb-2 mt-5 px-2 text-[11px] font-semibold uppercase leading-4 tracking-[0.055em] text-white/50 transition-[height,margin,opacity] duration-150", state === "collapsed" && "mb-2 mt-4 h-0 overflow-hidden px-0 opacity-0", className)} {...props} />; }
function SidebarMenu({ className, ...props }: React.HTMLAttributes<HTMLUListElement>) { return <ul className={cn("flex w-full min-w-0 flex-col gap-px", className)} {...props} />; }
function SidebarMenuItem({ className, ...props }: React.HTMLAttributes<HTMLLIElement>) { return <li className={cn("group/menu-item relative min-w-0", className)} {...props} />; }
const SidebarMenuButton = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement> & { isActive?: boolean; asChild?: boolean }>(({ className, isActive, asChild = false, ...props }, ref) => { const Comp = asChild ? Slot : "button"; return <Comp ref={ref} data-active={isActive || undefined} className={cn("interakt-nav-item group/menu-button relative -mx-3 flex h-[44px] w-[calc(100%+1.5rem)] min-w-0 touch-manipulation flex-row items-center gap-2.5 whitespace-nowrap rounded-md px-6 text-left text-[14px] font-medium leading-5 text-white/90 outline-none transition-[background-color,color,box-shadow,transform] duration-200 ease-out active:bg-white/[.14] active:scale-[.98] focus-visible:ring-2 focus-visible:ring-[#6ee7b7]/70 focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--sidebar-deep)] data-[active=true]:bg-white/[.055] data-[active=true]:font-semibold data-[active=true]:text-white data-[active=true]:before:absolute data-[active=true]:before:inset-y-0 data-[active=true]:before:left-0 data-[active=true]:before:h-full data-[active=true]:before:w-[3px] data-[active=true]:before:rounded-none data-[active=true]:before:bg-[#34d399] data-[active=true]:[&>span>svg]:text-[#6ee7b7]", className)} {...props} />; });
SidebarMenuButton.displayName = "SidebarMenuButton";
function SidebarMenuSub({ className, ...props }: React.HTMLAttributes<HTMLUListElement>) { return <ul className={cn("mx-3 flex min-w-0 translate-x-px flex-col border-l border-white/10 py-1.5 pl-3", className)} {...props} />; }
function SidebarMenuSubItem({ className, ...props }: React.HTMLAttributes<HTMLLIElement>) { return <li className={cn("relative min-w-0", className)} {...props} />; }
const SidebarMenuSubButton = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement> & { isActive?: boolean; asChild?: boolean }>(({ className, isActive, asChild = false, ...props }, ref) => { const Comp = asChild ? Slot : "button"; return <Comp ref={ref} data-active={isActive || undefined} className={cn("interakt-nav-item relative flex min-h-10 w-full touch-manipulation items-center rounded-md px-2 text-left text-[13px] font-normal text-white/60 outline-none transition-[background-color,color,box-shadow,transform] duration-200 ease-out active:bg-white/[.14] active:scale-[.98] focus-visible:ring-2 focus-visible:ring-[#6ee7b7]/70 data-[active=true]:bg-white/[.045] data-[active=true]:font-medium data-[active=true]:text-white data-[active=true]:before:absolute data-[active=true]:before:-left-[14px] data-[active=true]:before:top-0 data-[active=true]:before:h-full data-[active=true]:before:w-[3px] data-[active=true]:before:rounded-none data-[active=true]:before:bg-[#34d399]", className)} {...props} />; });
SidebarMenuSubButton.displayName = "SidebarMenuSubButton";
export { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarMenuSub, SidebarMenuSubItem, SidebarMenuSubButton };
