import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cn } from "@/lib/utils";
import { SidebarProvider as SidebarStateProvider, useSidebar } from "@/hooks/use-sidebar";

const SidebarProvider = SidebarStateProvider;
function Sidebar({ children, className, ...props }: React.HTMLAttributes<HTMLElement>) {
  const { state } = useSidebar();
  return <aside data-state={state} className={cn("fixed inset-y-0 left-0 z-30 hidden w-[var(--sidebar-width)] flex-col border-r border-[var(--border)] bg-white shadow-[3px_0_10px_rgba(30,40,55,0.09)] transition-[width] duration-150 ease-out md:flex", state === "collapsed" && "w-[var(--sidebar-collapsed-width)]", className)} {...props}>{children}</aside>;
}
function SidebarHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("shrink-0", className)} {...props} />; }
function SidebarContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("scrollbar-subtle min-h-0 flex-1 overflow-y-auto", className)} {...props} />; }
function SidebarFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("shrink-0", className)} {...props} />; }
function SidebarGroup({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("relative w-full min-w-0 px-3", className)} {...props} />; }
function SidebarGroupLabel({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { const { state } = useSidebar(); return <div className={cn("mb-2 mt-5 px-2 text-[13px] font-semibold uppercase leading-4 tracking-[-0.01em] text-[var(--brand)] transition-[height,margin,opacity] duration-150", state === "collapsed" && "mb-2 mt-4 h-0 overflow-hidden px-0 opacity-0", className)} {...props} />; }
function SidebarMenu({ className, ...props }: React.HTMLAttributes<HTMLUListElement>) { return <ul className={cn("flex w-full min-w-0 flex-col gap-px", className)} {...props} />; }
function SidebarMenuItem({ className, ...props }: React.HTMLAttributes<HTMLLIElement>) { return <li className={cn("group/menu-item relative min-w-0", className)} {...props} />; }
const SidebarMenuButton = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement> & { isActive?: boolean; asChild?: boolean }>(({ className, isActive, asChild = false, ...props }, ref) => { const Comp = asChild ? Slot : "button"; return <Comp ref={ref} data-active={isActive || undefined} className={cn("group/menu-button flex h-[45px] w-full min-w-0 flex-row items-center gap-2.5 whitespace-nowrap rounded-md px-2.5 text-left text-[15px] font-medium leading-normal text-[var(--text-primary)] outline-none transition-[background-color,color,box-shadow] duration-150 ease-out hover:bg-[var(--brand-soft)] hover:text-[var(--brand)] active:opacity-95 focus-visible:ring-2 focus-visible:ring-[var(--brand)]/20 data-[active=true]:h-10 data-[active=true]:bg-[var(--brand)] data-[active=true]:font-medium data-[active=true]:text-white data-[active=true]:shadow-[0_1px_3px_rgba(17,107,111,0.12),inset_0_0_0_1px_rgba(255,255,255,0.05)] data-[active=true]:hover:bg-[var(--brand-hover)]", className)} {...props} />; });
SidebarMenuButton.displayName = "SidebarMenuButton";
function SidebarMenuSub({ className, ...props }: React.HTMLAttributes<HTMLUListElement>) { return <ul className={cn("mx-3 flex min-w-0 translate-x-px flex-col border-l border-[var(--border-soft)] py-1.5 pl-3", className)} {...props} />; }
function SidebarMenuSubItem({ className, ...props }: React.HTMLAttributes<HTMLLIElement>) { return <li className={cn("relative min-w-0", className)} {...props} />; }
const SidebarMenuSubButton = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement> & { isActive?: boolean; asChild?: boolean }>(({ className, isActive, asChild = false, ...props }, ref) => { const Comp = asChild ? Slot : "button"; return <Comp ref={ref} data-active={isActive || undefined} className={cn("relative flex min-h-10 w-full items-center rounded-md px-2 text-left text-[14px] font-normal text-[var(--text-secondary)] outline-none transition-colors duration-150 hover:text-[var(--brand)] active:opacity-90 data-[active=true]:font-medium data-[active=true]:text-[var(--brand)] data-[active=true]:before:absolute data-[active=true]:before:-left-[14px] data-[active=true]:before:top-1 data-[active=true]:before:h-8 data-[active=true]:before:w-[3px] data-[active=true]:before:rounded-full data-[active=true]:before:bg-[var(--brand)]", className)} {...props} />; });
SidebarMenuSubButton.displayName = "SidebarMenuSubButton";
export { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarMenuSub, SidebarMenuSubItem, SidebarMenuSubButton };
