export const industryValues = [
  "marketing-advertising",
  "ecommerce",
  "entertainment-social-media-gaming",
  "education",
  "finance",
  "financial-services",
  "healthcare",
  "public-utilities-non-profits",
  "real-estate",
  "real-estate-construction",
  "retail",
  "technology",
  "travel-hospitality",
  "professional-services",
  "automotive",
  "restaurants",
  "manufacturing-impex",
  "fitness-wellness",
  "other",
] as const;
